server { listen 80; server_name _; root /usr/share/nginx/html; index index.html;
 location / { proxy_pass http://frontend:80; }
 location /api/products/ { proxy_pass http://product-api:3001/products/; }
 location = /api/products { proxy_pass http://product-api:3001/products; }
 location /api/inventory/ { proxy_pass http://inventory-api:3002/inventory/; }
 location = /api/inventory { proxy_pass http://inventory-api:3002/inventory; }
 location /api/sales/ { proxy_pass http://sales-api:3003/sales/; }
 location = /api/sales { proxy_pass http://sales-api:3003/sales; }
}
