import './style.css';
const app=document.querySelector('#app');const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
app.innerHTML=`<header><div><h1>StockWise</h1><p>Inventory & Sales Management</p></div><span class="version">Build ${esc(window.APP_VERSION||'local')}</span></header><nav><button data-page="dashboard">Dashboard</button><button data-page="products">Products</button><button data-page="inventory">Inventory</button><button data-page="sales">Sales</button></nav><main id="view">Loading…</main><footer>StockWise · Containerized Inventory System</footer>`;
const view=document.querySelector('#view');let page='dashboard';const api=async(path,opts={})=>{const r=await fetch('/api/'+path,{headers:{'Content-Type':'application/json'},...opts});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d};const money=n=>'₱'+Number(n||0).toFixed(2);const table=(headers,rows)=>`<div class="tablewrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${headers.length}">No records found</td></tr>`}</tbody></table></div>`;
async function render(){try{if(page==='dashboard'){const [p,i,s]=await Promise.all([api('products'),api('inventory'),api('sales')]);view.innerHTML=`<h2>Dashboard</h2><section class="cards"><article><small>Total Products</small><strong>${p.length}</strong></article><article><small>Total Stock Units</small><strong>${i.reduce((a,x)=>a+Number(x.quantity),0)}</strong></article><article><small>Low Stock Items</small><strong>${i.filter(x=>x.quantity<=x.low_stock_threshold).length}</strong></article><article><small>Sales Total</small><strong>${money(s.reduce((a,x)=>a+Number(x.total_amount),0))}</strong></article></section><h3>Recent sales</h3>${table(['ID','Product','Qty','Total','Date'],s.slice(0,5).map(x=>[x.id,esc(x.name),x.quantity,money(x.total_amount),esc(x.created_at)]))}`;
}else if(page==='products'){const p=await api('products');view.innerHTML=`<h2>Products</h2><form id="productForm"><input name="name" placeholder="Product name" required><input name="sku" placeholder="SKU" required><input name="category" placeholder="Category" value="General"><input name="price" type="number" min="0" step="0.01" placeholder="Price" required><button>Add product</button></form>${table(['ID','Name','SKU','Category','Price'],p.map(x=>[x.id,esc(x.name),esc(x.sku),esc(x.category),money(x.price)]))}`;document.querySelector('#productForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.price=Number(d.price);try{await api('products',{method:'POST',body:JSON.stringify(d)});render();}catch(err){alert(err.message)}};
}else if(page==='inventory'){const i=await api('inventory');view.innerHTML=`<h2>Inventory</h2><form id="stockForm"><input name="productId" type="number" min="1" placeholder="Product ID" required><input name="quantity" type="number" min="1" placeholder="Quantity received" required><button>Receive stock</button></form>${table(['Product ID','Product','SKU','Quantity','Low-stock threshold'],i.map(x=>[x.product_id,esc(x.name),esc(x.sku),x.quantity,x.low_stock_threshold]))}<h3>Low stock</h3>${table(['Product','SKU','Quantity'],i.filter(x=>x.quantity<=x.low_stock_threshold).map(x=>[esc(x.name),esc(x.sku),x.quantity]))}`;document.querySelector('#stockForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.productId=Number(d.productId);d.quantity=Number(d.quantity);try{await api('inventory/receive',{method:'POST',body:JSON.stringify(d)});render();}catch(err){alert(err.message)}};
}else{const [p,s]=await Promise.all([api('products'),api('sales')]);view.innerHTML=`<h2>Sales</h2><form id="saleForm"><select name="productId">${p.map(x=>`<option value="${x.id}">${esc(x.name)} — ${money(x.price)}</option>`).join('')}</select><input name="quantity" type="number" min="1" placeholder="Quantity" required><button>Record sale</button></form>${table(['ID','Product','Qty','Unit price','Total','Date'],s.map(x=>[x.id,esc(x.name),x.quantity,money(x.unit_price),money(x.total_amount),esc(x.created_at)]))}`;document.querySelector('#saleForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.productId=Number(d.productId);d.quantity=Number(d.quantity);try{await api('sales',{method:'POST',body:JSON.stringify(d)});render();}catch(err){alert(err.message)}};}}
catch(e){view.innerHTML=`<p class="error">Unable to load data: ${esc(e.message)}. Check that the containers and database are running.</p>`;}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});render();
